- branchtest.txt
Branching and publishing functionality test.
> Branch test

- IITS.ps1
Had some parameters defined that weren't needed.
> Cleaned up some extra parameters in Get-MailFlow

- app_version.ps1
- lock_user_pc.ps1
> Pull Request Test

- IITS.ps1
- README.md
Added function Get-EsetLink (alias Get-ESET). Also updated README file.
> Get-EsetLink

- IITS.ps1
> Removed Get-ServiceAccounts

- IITS.ps1
- README.md
Converted function list from bulleted list to table with included authors.
> Updated README (again)

- IITS.ps1
Cleaned up some code and added Get-ServiceAccount.  See function description for more information.
> Added Get-ServiceAccount

- IITS.ps1
- README.md
Deleted a line of testing-only code from Get-EsetLink; no longer needed.
> Minor Cleanup

- IITS.ps1
- README.md
Removed parameter for the key; I baked it in now that the location is static. Also just cleaned up the description in general.
Alphabetized the Readme (it was bugging me).
> Updated Get-EsetLink

- IITS.ps1
- README.md
> Resovled conflicts and updated files

- README.md
Just making my lines have caps to match standard
> Super Duper Minor/Fast Read.me edit

- Ger-All-App-Versions.ps1
- IITS.ps1
- README.md
> Updated for get-all-app-versions

- IITS.ps1
- README.md
From address has to be forecast@integratedit.com
> Cleaned up email-msalarm code and fixed from address

- IITS.ps1
Changed the subject line in the attachment branch.
> Fixed more errors in EMail-MSalarm

- IITS.ps1
- README.md
Updated script with new function and updated readme file.
> Added Get-DiskChanges

- IITS.ps1
- README.md
Now the function will only return fixed disks.
> Updated Get-DriveStatistics

- IITS.ps1
> Get-projection

- IITS.ps1
- README.md
Need VSS information for diskchanges.
> Added VSS information to Get-DiskChanges

- IITS.ps1
Projection script is added back to the IITS.ps1 file after discussion with DK 0818
> Projection

- IITS.ps1
- README.md
> Fixed DiskChanges Script

- README.md
For adding iVantage accounts to Chartis' 365
> add-ivantage-user

- IITS.ps1
- README.md
Needed to change it to patchemail.txt
> Had to modify the error file name

- IITS.ps1
Created new array to send to all clients from marketing manager csv file.
> Updated Send-PatchEmail

- IITS.ps1
- README.md
I have added the above function to the ps1 file. The function is to create a specific task only for USPG. The script was unable to be executed through Agent procedure. want to execute through github
> Added function create-uspgtaskrebootpopup

- Examples/Error Logging.txt
- IITS.ps1
Greatly reworked the structure and some functionality of Email-MSalarm. Added attachment validation, so now the script should no longer silently die if an attached file doesn't exist (whether actually or typo). Added comments to script.
Unrelated trivial update to Error Logging example file.
Unrelated cleanup of Get-KaseyaMachineID (just cleaning, no actual changes).
> Email-MSalarm rework

- IITS.ps1
Create-LocalAdministrator
get-iitstaskpswd
Created 2 functions , one to create a iitstask local administrator account on a machine and another script to retrieve the password of that account
> New Account Creation and Retrieval of password

- IITS.ps1
- README.md
A function with the above name was created to collect the error evnts from System and Application logs that took place in the last month
> Get-ErrorEventLogs

- IITS.ps1
- PS_Examples.ps1
- README.md
Created the above function that will send an e-mail if 2 consecutive runs of a custom IITS task has failed.
> created function check-IITStasks
